name: Refresh Instagram access token

on:
  schedule:
    - cron: '0 0 1 * *' # de eerste dag van elke maand op middernacht
  workflow_dispatch:

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    steps:
      - name: curl to ping instagram server
        env:
          instagram_access_token: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
        run: curl -X GET 'https://graph.instagram.com/refresh_access_token?grant_type=ig_refresh_token&access_token=$instagram_access_token'