name: update

on:
  schedule:
    - cron: '*/30 8-17 * * *' # elk halfuur van 8 uur 's ochtends tot 17 uur 's avonds
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo pages # checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # installeer de correcte versie van Python

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: execute py script # update via script
        env:
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
          youtube_channel_id: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        run: |
          wget https://raw.githubusercontent.com/oinc-olva/oinc-olva.github.io/main/update/update.py -O update.py
          python update.py
          rm update.py

      - name: commit # Commit aanpassingen
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "🚀 Automatische vernieuwing van website" -a

      - name: push changes # Push aanpassingen
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          branch: gh-pages